locallibrary/catalog/urls.py
from django.urls import path

from . import views
# from catalog.views import BookListView, index


urlpatterns = [
    path('', views.index, name='index' ),
    path('books/',views.BookListView.as_view(), name='books'),
    path('book/<int:pk>',views.BookDetailView.as_view(), name='book-detail'),
    path('authors',views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',views.AuthorDetailView.as_view(), name='author-detail')

    
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('catalog.urls')),
]

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances

# Create your models here.

class Genre(models.Model):
	name = models.CharField(max_length=200, help_text='Enter a book genre(e.g. Science Fiction)')

	def __str__(self):
		return self.name


class Author(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField(null=True, blank=True)

	class Meta:
		ordering = ['last_name', 'first_name']

	def get_absolute_url(self):
		return reverse('author-detail', args = [str(self.id)])


	def __str__(self):
		# return f'{self.last_name} ({self.first_name})'
		return '%s %s' % (self.last_name, self.first_name)





class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
	title = models.CharField(max_length=200, help_text='enter the title of book')
	author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
	summary = models.TextField(max_length=1000, help_text='Enter the brief description of the book')
	isbn = models.CharField(max_length=13, help_text='Enter 13 digit <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	genre = models.ManyToManyField(Genre, help_text='Select a Genre for this book')
	language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		"""Create a string for the Genre. This is required to display genre in Admin."""
		return ', '.join(genre.name for genre in self.genre.all()[:3])

	display_genre.short_description = 'Genre'



class BookInstance(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
	book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)
	author =models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)

	LOAN_STATUS = (
		('m','Maintanance'),
		('o','On Loan'),
		('a','Available'),
		('r','Reserved'),
		)
	status = models.CharField(max_length=1,choices=LOAN_STATUS, blank=True,default='m', help_text='Book Availibility')

	class Meta:
		ordering = ['due_back']

	def __str__(self):		
		return '%s %s' %(self.id, self.book.title)

locallibrary/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from catalog.models import Book, BookInstance, Author


from django.views.generic import ListView, DetailView

# Create your views here.

def index(request):
	# return HttpResponse('<h1>Welcome</h1>')
	num_books = Book.objects.all().count()
	num_instances = BookInstance.objects.all().count()
	num_instances_available = BookInstance.objects.filter(status__exact='a').count()
	num_authors = Author.objects.count()
	# Get a session value, setting a default if it is not present
	num_visits = request.session.get('num_visits',0)
	request.session['num_visits'] = num_visits + 1

	context={
	'num_books':num_books,
	'num_instances':num_instances,
	'num_instances_available':num_instances_available,
	'num_authors':num_authors,
	'num_visits':num_visits,

	}
	return render(request,'index.html',context=context)



class BookListView(ListView):	
	model = Book
	context_object_name ='my_book_list'
	# your own name for the list as a template variable
	queryset = Book.objects.all()
	paginate_by = 10
	# queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
	template_name = 'my_book_list.html'  # Specify your own template name/location


class BookDetailView(DetailView):
	print('check detail')
	model = Book
	context_object_name ='bookdetail'	
	queryset = Book.objects.all()
	
	template_name = 'book_detail.html'  # Specify your own template name/location



class AuthorListView(ListView):
	queryset = Author.objects.all()
	context_object_name='author'
	template_name = 'author_list.html'
	
	def get_context_data(self, **kwargs):
		context = super(AuthorListView, self).get_context_data(**kwargs)
		context['bk']=Book.objects.all()
		return context


class AuthorDetailView(DetailView):
	model = Author
	context_object_name ='authordetail'
	queryset = Author.objects.all()
	template_name = 'author_detail.html'


	def get_context_data(self, **kwargs):
		context = super(AuthorDetailView, self).get_context_data(**kwargs)
		context['book'] = Book.objects.filter(author=self.author_name)
		return context
	

locallibrary/catalog/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Author Detail</h1>

{% if authordetail %}


<p><strong>Author Full name : </strong> {{authordetail.first_name}} {{ authordetail.last_name }}</p>


{% if authordetail.date_of_death %}

<p><strong>Date of Birth :</strong>{{ authordetail.date_of_birth }}</p>

<p><strong>Date of Death :</strong>{{ authordetail.date_of_death }}</p>
{% else %}

<p><strong>Date of Birth :</strong>{{ authordetail.date_of_birth }}</p>

<p>Book: {{ authordetail.pk }}</p>




<div style="margin-left:20px;margin-top:20px">
<h4>Books</h4>

<dl>
{% for book in authordetail.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
{% endfor %}
</dl>

</div>

{% endif %}
{% endif %}
{% endblock %}

locallibrary/catalog/templates/author_list.html
{% extends "base.html" %}
{% block content %}
<h1>Author list</h1>
 

{% if author %}
{% for author in author %}

<ul>
	<li><a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> {{ author.last_name }}</li>
</ul>


{% endfor %}

{% endif %}
{% endblock %}

locallibrary/catalog/templates/base.html
<!DOCTYPE html>
<html>
<head>
	{% block title %}<title>Local Library</title>{% endblock %}

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% load static %}
 <link rel="stylesheet" href="{% static 'css/styles.css' %}">



</head>
<body>
	<div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
         <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}





      {% endblock %}

       {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}  



    </div>


    </div>
  </div>
</body>
</html>

locallibrary/catalog/templates/book_detail.html
{% extends "base.html" %}

<h2>BOOK DETAIL</h2>

{% block content %}
{% if bookdetail %}
<p><strong>Title:</strong>{{bookdetail.title}}</p>
<p><strong>Author:</strong>{{bookdetail.author}}</p>
<p><strong>Description:</strong>{{bookdetail.summary}}</p>
<p><strong>ISBN:</strong>{{bookdetail.isbn}}</p>
<p><strong>GENRE:</strong>{{bookdetail.genre.name}}</p>

{% endif %}
{% endblock %}

locallibrary/catalog/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

  <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

locallibrary/catalog/templates/my_book_list.html
{% extends "base.html" %}

{% block content %}

<h1>Book List </h1>


{% if my_book_list %}
<ul>
{% for book in my_book_list %}

	<li>		
		<a href="{{ book.get_absolute_url }}">{{ book.title }}</a> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a>
	</li>

{% endfor %}
</ul>

{% else %}
<h1>No record found</h1>
{% endif %}



{% endblock %}